import {Inter} from 'next/font/google'
import './globals.css'
import React from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <div className="w-full h-full flex flex-col">
        <Header/>
        <main className={"grow overflow-x-hidden overflow-y-auto overscroll-none"}>
          <div className={"container mx-auto px-4 py-6"}>{children}</div>
        </main>
        <Footer/>
      </div>
    </body>
    </html>
  )
}
